### PR TITLE
some stuff

### PR DESCRIPTION
**Pull request by glitchyfishys**
need to fix EC5 for V's reality
I did it :)

### CODE REVIEW

**Comment by glitchyfishys** [comment]
`window.decimalCubicSolution = function decimalCubicSolution(a, b, c, d, n = false) {
  const delta0 = b.pow(2).sub(a.times(3).times(c));
  const delta1 = b.pow(2).times(2).sub(a.times(b).times(c).times(9)).add(a.pow(2).times(d).times(27));
  const ne = n ? Decimal.sqrt(delta1.pow(2).sub(delta0.pow(3).times(4)))
    : Decimal.root(delta1.pow(2).sub(delta0.pow(3).times(4)), 2);
  const C = Decimal.cbrt(delta1.add(ne).div(2));
  const x = DC.D1.div(a.times(3)).neg().times(b.add(C).add(delta0.div(C)));
  return x;
};`

this may fix EC5

**Comment by Donaldino7712** [comment]
This PR has merge conflicts, please resolve them

**Comment by HexaVault** [comment]
consider making a draft pr till necessary?

**Comment by HexaVault** [comment]
Most of these are being fixed in an upcoming patch and some of your code is either incorrect or will cause issues. Feel free to open a new pr with only the necessary changes rather than creating large prs like this, as they are difficult to look through.

**Pull request closed without merging**
