### PR TITLE
Apply the bulk of changes from upstream post-open-source

### PR DESCRIPTION
**Pull request by James103**
This updates the BE port with most of the changes that have occurred since the open-sourcing of the vanilla game. Most of the changes are bug fixes, but this also makes the sidebar resource customizable.

Most of the commits are untested due to unrelated errors that occur while importing vanilla saves.

### CODE REVIEW

**Review by HexaVault — CHANGES_REQUESTED** [review]
114 of reality.js needs to be looked at

**Comment by HexaVault** [comment]
I've updated my comment to be correct (it originally stated a file that did not exist)

Notation changes should be fine, since afaik the notation code was only done post-patches. Minor bugs might exist, but if needed I can manually sort them out.

**Comment by James103** [comment]
> Notation changes should be fine, since afaik the notation code was only done post-patches. Minor bugs might exist, but if needed I can manually sort them out.

Porting over the relevant commits listed below gives a working modal allowing the player to change the minimum number of digits necessary to show commas or notation in the exponent; however, this is currently nonfunctional for all notations.
image

* https://github.com/IvarK/AntimatterDimensionsSourceCode/commit/6bc1a0b50cd4747e54bea7a59b5102d355cf615e
* https://github.com/IvarK/AntimatterDimensionsSourceCode/commit/772ab98ab16c5ad5de91bcc4956012394172291d
* https://github.com/IvarK/AntimatterDimensionsSourceCode/commit/745c5585dff23e06f63efc438d56aff92b91d200

**Comment by HexaVault** [comment]
> > Notation changes should be fine, since afaik the notation code was only done post-patches. Minor bugs might exist, but if needed I can manually sort them out.
> 
> Porting over the relevant commits listed below gives a working modal allowing the player to change the minimum number of digits necessary to show commas or notation in the exponent; however, this is currently nonfunctional for all notations. image
> 
> * [IvarK/AntimatterDimensionsSourceCode@6bc1a0b](https://github.com/IvarK/AntimatterDimensionsSourceCode/commit/6bc1a0b50cd4747e54bea7a59b5102d355cf615e)
> * [IvarK/AntimatterDimensionsSourceCode@772ab98](https://github.com/IvarK/AntimatterDimensionsSourceCode/commit/772ab98ab16c5ad5de91bcc4956012394172291d)
> * [IvarK/AntimatterDimensionsSourceCode@745c558](https://github.com/IvarK/AntimatterDimensionsSourceCode/commit/745c5585dff23e06f63efc438d56aff92b91d200)

You will need to change the code to do `import * as ADNotations from "adnot-beport-small";` instead

**Comment by James103** [comment]
I have updated the relevant line and pushed the notation changes as they all work now.

**Review by HexaVault — APPROVED** [review]

**Pull request merged**
